# Generated by Django 2.1.5 on 2019-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_title', models.CharField(max_length=200)),
                ('demo_description', models.CharField(max_length=200)),
            ],
        ),
    ]
